/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CuratorOrganization.DataCollectorRole;

import Business.Constant;
import Business.EcoSystem;
import Business.Enterpise.Enterprise;
import Business.Network.Network;
import Business.Organization.DataCollectorOrganization;
import Business.Organization.JobRequestManagerOrganization;
import Business.Organization.Organization;
import Business.Organization.TrainingRequestManagerOrganization;
import Business.Questionnaire.Questionnaire;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.JobWorkRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanch
 */
public class ManageRecordsJPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
    private DataCollectorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;
    WorkRequest workRequest;
    Questionnaire questionnaire;
    /**
     * Creates new form ManageRecordsJPanel
     */
    public ManageRecordsJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.organization =(DataCollectorOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
         loggedinLabel2.setText(userAccount.getEmployee().getName());
        orgLbl2.setText(organization.getName());
        roleLbl2.setText(userAccount.getRole().toString());
     
        populateRequestTable();
    }
public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();
        ArrayList<WorkRequest> worklist = new ArrayList<>();
        model.setRowCount(0);
        for(Network net : business.getNetworkList()){
                if(net.getName().equalsIgnoreCase(enterprise.getNetworkName()))
                {
                    for(Enterprise enter: net.getEnterpriseDirectory().getEnterpriseList()){
                        for (Organization org : enter.getOrganizationList().getOrganizationList()){
                            if(org instanceof JobRequestManagerOrganization || org instanceof TrainingRequestManagerOrganization){
                                for(WorkRequest wk : org.getWorkQueue().getWorkRequestList()){
                                    worklist.add(wk);
                                }
                            }
                        }
                    }
                }
                
        }
                        
         //WorkRequest request =organization.getWorkQueue().getWorkRequestList()
                 for(WorkRequest request :worklist){
                     Object[] row = new Object[4];
                     row[0] =request;
                     row[1] = request.getQuestionaire().getPersonalQuestionnaire().getName();
                     row[2] = request.getQuestionaire().getPersonalQuestionnaire().getRequestType();
                     row[3] = request.getStatus();
                     model.addRow(row);
                 }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        viewRecordButton = new javax.swing.JButton();
        btnNotification = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        loggedinLabel2 = new javax.swing.JLabel();
        roleLbl2 = new javax.swing.JLabel();
        orgLbl2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        backJBtn.setBackground(new java.awt.Color(0, 102, 255));
        backJBtn.setText("<< Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Name", "Request Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestTable);

        viewRecordButton.setBackground(new java.awt.Color(102, 255, 102));
        viewRecordButton.setText("View Record");
        viewRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecordButtonActionPerformed(evt);
            }
        });

        btnNotification.setText("Send Notification");
        btnNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificationActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("User Details"));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Log In as :");

        loggedinLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loggedinLabel2.setText("jLabel2");

        roleLbl2.setText("jLabel2");

        orgLbl2.setText("jLabel3");

        jLabel16.setText("Enterprise");

        jLabel18.setText("Role :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Manage Records Area");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(roleLbl2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(orgLbl2)
                        .addContainerGap(667, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(loggedinLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(loggedinLabel2)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(orgLbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(roleLbl2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(btnNotification)
                                .addGap(46, 46, 46)
                                .addComponent(viewRecordButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backJBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNotification)
                    .addComponent(viewRecordButton))
                .addGap(172, 172, 172))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void viewRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecordButtonActionPerformed

         int selectedRow = requestTable.getSelectedRow();
       WorkRequest request =null;

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (selectedRow >= 0) {
            request = (WorkRequest)requestTable.getValueAt(selectedRow, 0);
            if(request.getStatus().equalsIgnoreCase(Constant.TR_REQUESTSTATUS_PROCESSED)){
                JOptionPane.showMessageDialog(null, "Processed Request cannot be updated.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
            }
            questionnaire =request.getQuestionaire();
           
            UpdateRecordJPanel UpdateRecordJPanel = new UpdateRecordJPanel(userProcessContainer, business, request,userAccount,organization);
            userProcessContainer.add("UpdateRecordJPanel", UpdateRecordJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();

            layout.next(userProcessContainer);
            
    }                                             
    }//GEN-LAST:event_viewRecordButtonActionPerformed

    private void btnNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificationActionPerformed
        // TODO add your handling code here:
        int selectedRow = requestTable.getSelectedRow();
       WorkRequest request =null;

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (selectedRow >= 0) {
            request = (WorkRequest)requestTable.getValueAt(selectedRow, 0);
            if(request.getStatus().equalsIgnoreCase(Constant.TR_REQUESTSTATUS_PROCESSED)){
                questionnaire =request.getQuestionaire();
                workRequest =request;
                boolean isSend =questionnaire.getPersonalQuestionnaire().getIsNotified() == null ? false :true;
             if(!isSend )
            {
                    try {
                        if(request.getQuestionaire().getPersonalQuestionnaire().getRequestType().equalsIgnoreCase(Constant.TR_REQUESTTYPE_JOB)){
                            
                        
                        sendJobEmailWithAttachments();
                        }
                        else
                        {
                            sendEduEmailWithAttachments();
                        }
                        questionnaire.getPersonalQuestionnaire().setIsNotified(Boolean.TRUE);
                    } catch (MessagingException ex) {
                        Logger.getLogger(ManageRecordsJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(ManageRecordsJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
             else
             {
                 JOptionPane.showMessageDialog(null, "Email Notification already sent to Person.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
             }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Person will be notified once request is processed.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        JOptionPane.showMessageDialog(null, "Email notification sent successfully!!!", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnNotificationActionPerformed
    public  void sendJobEmailWithAttachments()
            throws AddressException, MessagingException, IOException {
        String host = Constant.TR_NOTIFICATIONHOST;
        String port = Constant.TR_NOTIFICATIONHOSTPORT;
        String userName = Constant.TR_NOTIFICATIONEMAIL;
        String password = Constant.TR_NOTIFICATIONPASSWORD;
        String subject ="Job Notification from Poverty Alleviation Sytem";
        String message = "Congratualtion you got hired." + workRequest.getReceiver() + " hired you.You will be notified for futher instruction."+
                 "Details will be given to on address " + questionnaire.getPersonalQuestionnaire().getAddress() + ",mobile number "
                + questionnaire.getPersonalQuestionnaire().getContact();
        // sets SMTP server properties
        Properties properties = new Properties();
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", port);
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.user", userName);
        properties.put("mail.password", password);
 
        // creates a new session with an authenticator
        Authenticator auth = new Authenticator() {
            public PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(userName, password);
            }
        };
        Session session = Session.getInstance(properties, auth);
 
        // creates a new e-mail message
        Message msg = new MimeMessage(session);
 
        msg.setFrom(new InternetAddress(userName));
        InternetAddress[] toAddresses = { new InternetAddress(questionnaire.getPersonalQuestionnaire().getEmailAddress()) };
        msg.setRecipients(Message.RecipientType.TO, toAddresses);
        msg.setSubject(subject);
        msg.setSentDate(new Date());
 
        // creates message part
        MimeBodyPart messageBodyPart = new MimeBodyPart();
        messageBodyPart.setContent(message, "text/html");
 
        // creates multi-part
        Multipart multipart = new MimeMultipart();
        multipart.addBodyPart(messageBodyPart);
 
        // adds attachments
//        if (attachFiles != null && attachFiles.length > 0) {
//            for (String filePath : attachFiles) {
//                MimeBodyPart attachPart = new MimeBodyPart();
// 
//                try {
//                    attachPart.attachFile(filePath);
//                } catch (IOException ex) {
//                    ex.printStackTrace();
//                }
// 
//                multipart.addBodyPart(attachPart);
//            }
//        }
 
        // sets the multi-part as e-mail's content
        msg.setContent(multipart);
 
        // sends the e-mail
        Transport.send(msg);
 
    }
    
    public  void sendEduEmailWithAttachments()
            throws AddressException, MessagingException, IOException {
        String host = Constant.TR_NOTIFICATIONHOST;
        String port = Constant.TR_NOTIFICATIONHOSTPORT;
        String userName = Constant.TR_NOTIFICATIONEMAIL;
        String password = Constant.TR_NOTIFICATIONPASSWORD;
        String subject ="Training Education Notification from Poverty Alleviation Sytem";
        String message = "Congratualtion you got shortlisted for training." + workRequest.getReceiver() + " training institute selected you based on your interest.You will be notified for futher instruction."+
                 "Details will be given to on address " + questionnaire.getPersonalQuestionnaire().getAddress() + ",mobile number "
                + questionnaire.getPersonalQuestionnaire().getContact();
        // sets SMTP server properties
        Properties properties = new Properties();
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", port);
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.user", userName);
        properties.put("mail.password", password);
 
        // creates a new session with an authenticator
        Authenticator auth = new Authenticator() {
            public PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(userName, password);
            }
        };
        Session session = Session.getInstance(properties, auth);
 
        // creates a new e-mail message
        Message msg = new MimeMessage(session);
 
        msg.setFrom(new InternetAddress(userName));
        InternetAddress[] toAddresses = { new InternetAddress(questionnaire.getPersonalQuestionnaire().getEmailAddress()) };
        msg.setRecipients(Message.RecipientType.TO, toAddresses);
        msg.setSubject(subject);
        msg.setSentDate(new Date());
 
        // creates message part
        MimeBodyPart messageBodyPart = new MimeBodyPart();
        messageBodyPart.setContent(message, "text/html");
 
        // creates multi-part
        Multipart multipart = new MimeMultipart();
        multipart.addBodyPart(messageBodyPart);
 
        // adds attachments
//        if (attachFiles != null && attachFiles.length > 0) {
//            for (String filePath : attachFiles) {
//                MimeBodyPart attachPart = new MimeBodyPart();
// 
//                try {
//                    attachPart.attachFile(filePath);
//                } catch (IOException ex) {
//                    ex.printStackTrace();
//                }
// 
//                multipart.addBodyPart(attachPart);
//            }
//        }
 
        // sets the multi-part as e-mail's content
        msg.setContent(multipart);
 
        // sends the e-mail
        Transport.send(msg);
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton btnNotification;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loggedinLabel2;
    private javax.swing.JLabel orgLbl2;
    private javax.swing.JTable requestTable;
    private javax.swing.JLabel roleLbl2;
    private javax.swing.JButton viewRecordButton;
    // End of variables declaration//GEN-END:variables
}
