/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CuratorOrganization.TrainingManagerRole;

import Business.EcoSystem;
import Business.Enterpise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.TrainingProcessOrganization;
import Business.Organization.TrainingRequestManagerOrganization;
import Business.Questionnaire.FamilyBackgroundQuestionaire;
import Business.Questionnaire.Questionnaire;
import Business.Questionnaire.TrainingQuestionaire;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TrainingRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sanch
 */
public class AddTrainingRequestDetailsJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private TrainingRequestManagerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;
    TrainingRequest request;
    boolean isRequested=false;
    /**
     * Creates new form ManageTraining
     */
    public AddTrainingRequestDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, TrainingRequestManagerOrganization organization, Enterprise enterprise, EcoSystem business,TrainingRequest workrequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization =(TrainingRequestManagerOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        this.request = workrequest;
        populateWorkRequestData();
        loggedinLabel5.setText(userAccount.getEmployee().getName());
        roleLbl5.setText(userAccount.getRole().toString());
        orgLbl5.setText(organization.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainingCombo = new javax.swing.ButtonGroup();
        disabilityCombo = new javax.swing.ButtonGroup();
        specificCombo = new javax.swing.ButtonGroup();
        familyCombo = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        jobPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        receivedTrainingNo = new javax.swing.JRadioButton();
        receivedTrainingYes = new javax.swing.JRadioButton();
        skillLabel = new javax.swing.JLabel();
        trainingType = new javax.swing.JComboBox<>();
        educationPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        disabilityNo = new javax.swing.JRadioButton();
        disabilityYes = new javax.swing.JRadioButton();
        disableLabel = new javax.swing.JLabel();
        disabilityType = new javax.swing.JComboBox<>();
        familyBackPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nuclearRadioBtn = new javax.swing.JRadioButton();
        siblingRadioBtn = new javax.swing.JRadioButton();
        parentRadioBtn = new javax.swing.JRadioButton();
        extendedRadioBtn = new javax.swing.JRadioButton();
        criminalPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        trainingDurationCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        specificComboYes = new javax.swing.JRadioButton();
        specificComboNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        seekLabel = new javax.swing.JLabel();
        trainingInterestCombo = new javax.swing.JComboBox<>();
        btnRequestJob = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        loggedinLabel5 = new javax.swing.JLabel();
        roleLbl5 = new javax.swing.JLabel();
        orgLbl5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jobPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Have you ever received any specific skill training ?");

        trainingCombo.add(receivedTrainingNo);
        receivedTrainingNo.setText("No");
        receivedTrainingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedTrainingNoActionPerformed(evt);
            }
        });

        trainingCombo.add(receivedTrainingYes);
        receivedTrainingYes.setText("Yes");
        receivedTrainingYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedTrainingYesActionPerformed(evt);
            }
        });

        skillLabel.setText("In which field have you received training ?");
        skillLabel.setEnabled(false);

        trainingType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical Labor", "Carpentry", "Mechanic", "Security", "Construction", "Cleaning", "Other" }));
        trainingType.setEnabled(false);

        javax.swing.GroupLayout jobPanelLayout = new javax.swing.GroupLayout(jobPanel);
        jobPanel.setLayout(jobPanelLayout);
        jobPanelLayout.setHorizontalGroup(
            jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jobPanelLayout.createSequentialGroup()
                        .addComponent(receivedTrainingYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receivedTrainingNo))
                    .addComponent(jLabel2)
                    .addComponent(skillLabel))
                .addContainerGap(748, Short.MAX_VALUE))
        );
        jobPanelLayout.setVerticalGroup(
            jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receivedTrainingYes)
                    .addComponent(receivedTrainingNo))
                .addGap(18, 18, 18)
                .addComponent(skillLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trainingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Training History", jobPanel);

        educationPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Do you have any kind of disability ?");

        disabilityCombo.add(disabilityNo);
        disabilityNo.setText("No");
        disabilityNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityNoActionPerformed(evt);
            }
        });

        disabilityCombo.add(disabilityYes);
        disabilityYes.setText("Yes");
        disabilityYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityYesActionPerformed(evt);
            }
        });

        disableLabel.setText("What kind of disability do you have ?");
        disableLabel.setEnabled(false);

        disabilityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vision", "Physical", "Speaking", "Hearing", "Other" }));
        disabilityType.setEnabled(false);

        javax.swing.GroupLayout educationPanelLayout = new javax.swing.GroupLayout(educationPanel);
        educationPanel.setLayout(educationPanelLayout);
        educationPanelLayout.setHorizontalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addComponent(disabilityYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disabilityNo))
                    .addComponent(disableLabel)
                    .addComponent(disabilityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(812, Short.MAX_VALUE))
        );
        educationPanelLayout.setVerticalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disabilityYes)
                    .addComponent(disabilityNo))
                .addGap(18, 18, 18)
                .addComponent(disableLabel)
                .addGap(18, 18, 18)
                .addComponent(disabilityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Disabilities", educationPanel);

        familyBackPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("What Type of family you are in: ");

        familyCombo.add(nuclearRadioBtn);
        nuclearRadioBtn.setText("Nuclear");

        familyCombo.add(siblingRadioBtn);
        siblingRadioBtn.setText("Sibling Household");

        familyCombo.add(parentRadioBtn);
        parentRadioBtn.setText("Single Parent");

        familyCombo.add(extendedRadioBtn);
        extendedRadioBtn.setText("Extended");

        javax.swing.GroupLayout familyBackPanelLayout = new javax.swing.GroupLayout(familyBackPanel);
        familyBackPanel.setLayout(familyBackPanelLayout);
        familyBackPanelLayout.setHorizontalGroup(
            familyBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(familyBackPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(nuclearRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(siblingRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parentRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(extendedRadioBtn)
                .addContainerGap(469, Short.MAX_VALUE))
        );
        familyBackPanelLayout.setVerticalGroup(
            familyBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(familyBackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(familyBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nuclearRadioBtn)
                    .addComponent(siblingRadioBtn)
                    .addComponent(parentRadioBtn)
                    .addComponent(extendedRadioBtn))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Family Background Information", familyBackPanel);

        criminalPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Select a training duration.");

        trainingDurationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 month", "3 months", "6 months", "12 months", "Any Duration" }));

        javax.swing.GroupLayout criminalPanelLayout = new javax.swing.GroupLayout(criminalPanel);
        criminalPanel.setLayout(criminalPanelLayout);
        criminalPanelLayout.setHorizontalGroup(
            criminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criminalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(criminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(trainingDurationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(864, Short.MAX_VALUE))
        );
        criminalPanelLayout.setVerticalGroup(
            criminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criminalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trainingDurationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Training Duration", criminalPanel);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setEnabled(false);

        specificCombo.add(specificComboYes);
        specificComboYes.setText("Yes");
        specificComboYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificComboYesActionPerformed(evt);
            }
        });

        specificCombo.add(specificComboNo);
        specificComboNo.setText("No");
        specificComboNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificComboNoActionPerformed(evt);
            }
        });

        jLabel4.setText("Do you  have any specific interest in which you seek training ?");

        seekLabel.setText("Training Type:");
        seekLabel.setEnabled(false);

        trainingInterestCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carpentry", "Security", "Construction", "Other" }));
        trainingInterestCombo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(specificComboYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(specificComboNo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(seekLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trainingInterestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(specificComboYes)
                    .addComponent(specificComboNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seekLabel)
                    .addComponent(trainingInterestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jTabbedPane.addTab("Specific Interests", jPanel2);

        btnRequestJob.setBackground(new java.awt.Color(51, 255, 51));
        btnRequestJob.setText("Request Training");
        btnRequestJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestJobActionPerformed(evt);
            }
        });

        backJBtn.setBackground(new java.awt.Color(255, 51, 51));
        backJBtn.setText("<< Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("User Details"));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Log In as :");

        loggedinLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loggedinLabel5.setText("jLabel2");

        roleLbl5.setText("jLabel2");

        orgLbl5.setText("jLabel3");

        jLabel18.setText("Organization :");

        jLabel19.setText("Role :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Training Manager Work Area");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(roleLbl5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(orgLbl5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(loggedinLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20)))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(loggedinLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(orgLbl5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(roleLbl5))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(backJBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(btnRequestJob)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane)
                .addGap(18, 18, 18)
                .addComponent(btnRequestJob)
                .addGap(56, 56, 56)
                .addComponent(backJBtn)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void receivedTrainingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedTrainingNoActionPerformed
        skillLabel.setEnabled(false);
        trainingType.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_receivedTrainingNoActionPerformed

    private void receivedTrainingYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedTrainingYesActionPerformed
        // TODO add your handling code here:
        skillLabel.setEnabled(true);
        trainingType.setEnabled(true);
    }//GEN-LAST:event_receivedTrainingYesActionPerformed

    private void disabilityNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityNoActionPerformed
        // TODO add your handling code here:
        disabilityType.setEnabled(false);
        disableLabel.setEnabled(false);
    }//GEN-LAST:event_disabilityNoActionPerformed

    private void disabilityYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityYesActionPerformed
        // TODO add your handling code here:
        disabilityType.setEnabled(true);
        disableLabel.setEnabled(true);
    }//GEN-LAST:event_disabilityYesActionPerformed

    private void specificComboYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificComboYesActionPerformed
        // TODO add your handling code here:
        seekLabel.setEnabled(true);
        //        specificComboYes.setSelected(true);
        trainingInterestCombo.setEnabled(true);
    }//GEN-LAST:event_specificComboYesActionPerformed

    private void specificComboNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificComboNoActionPerformed
        // TODO add your handling code here:
        seekLabel.setEnabled(false);
        //        specificComboYes.setSelected(false);
        trainingInterestCombo.setEnabled(false);
    }//GEN-LAST:event_specificComboNoActionPerformed

    private void btnRequestJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestJobActionPerformed
        // TODO add your handling code here:
        if(!isRequested){
        Questionnaire questionnaire = request.getQuestionaire();//business.getQuestionnaireList().addQuestionnaire();
        questionnaire.setIsDetailsSet(true);
        TrainingQuestionaire trainingQuestionaire = questionnaire.getTrainingQuestionaire() ;
        trainingQuestionaire.setTrained(receivedTrainingYes.isSelected());
        trainingQuestionaire.setDisabled(disabilityYes.isSelected());
        trainingQuestionaire.setSpecificInterest(specificComboYes.isSelected());
        if(disabilityYes.isSelected())
        {
            trainingQuestionaire.setDisability((String) disabilityType.getSelectedItem());
        }
        else if(disabilityNo.isSelected()){
            trainingQuestionaire.setDisability("None");
        }
        if(specificComboYes.isSelected()){

            trainingQuestionaire.setInterest((String) trainingInterestCombo.getSelectedItem());

        }
        else if(specificComboNo.isSelected()){
            trainingQuestionaire.setInterest("None");
        }
        trainingQuestionaire.setTrainingDuration((String) trainingDurationCombo.getSelectedItem());
        if(receivedTrainingYes.isSelected()){
            trainingQuestionaire.setTrainingField((String) trainingType.getSelectedItem());
        }
        else if(receivedTrainingNo.isSelected()){
            trainingQuestionaire.setTrainingField("None");
        }

        FamilyBackgroundQuestionaire FamilyBackgroundQuestionaire = questionnaire.getFamilyBackgroundQuestionaire();
        String strfamily="";
        if(nuclearRadioBtn.isSelected()){
            strfamily = nuclearRadioBtn.isSelected() ? "Nuclear" : "";
        }
        else if (siblingRadioBtn.isSelected()){
            strfamily = siblingRadioBtn.isSelected() ? "Sibling" : "";
        }
        else if (extendedRadioBtn.isSelected()){
            strfamily = extendedRadioBtn.isSelected() ? "Extended" : "";
        }
        else if (parentRadioBtn.isSelected()){
            strfamily = parentRadioBtn.isSelected() ? "SingleParent" : "";
        }
        FamilyBackgroundQuestionaire.setFamilyBackground(strfamily);

        Organization org = null;
        for(Network network :business.getNetworkList()){
            if(network.getName().equalsIgnoreCase(enterprise.getNetworkName())){
                for(Enterprise et : network.getEnterpriseDirectory().getEnterpriseList()){

                    for (Organization organization : et.getOrganizationList().getOrganizationList()){

                        if (organization instanceof TrainingProcessOrganization){
                            org = organization;
                            break;
                        }

                    }
                }
            }
        }
        if (org!=null){

            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setQuestionaire(questionnaire);
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);

        }
        JOptionPane.showMessageDialog(null, "Individual request created successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);
        isRequested = true;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Request already forwarded", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRequestJobActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed
    private void populateWorkRequestData(){
        Questionnaire questionaire = request.getQuestionaire();
        if(questionaire.isIsDetailsSet()){
        String training = questionaire.getTrainingQuestionaire().getTrainingField().equalsIgnoreCase("None") ?"":questionaire.getTrainingQuestionaire().getTrainingField();
        if(!training.equalsIgnoreCase("")){
        trainingType.setSelectedItem(training );
        trainingType.setEnabled(true);
        receivedTrainingYes.setSelected(true);
        
        }
        else
        {
            receivedTrainingYes.setSelected(false);
        }
        String disability = questionaire.getTrainingQuestionaire().getDisability().equalsIgnoreCase("None") ?"":questionaire.getTrainingQuestionaire().getDisability();
        if(!disability.equalsIgnoreCase("")){
            disabilityType.setEnabled(true);
        disabilityType.setSelectedItem(disability );
        disabilityYes.setSelected(true);
        }
        else
        {
            disabilityYes.setSelected(false);
        }
        String Interest = questionaire.getTrainingQuestionaire().getInterest().equalsIgnoreCase("None") ?"":questionaire.getTrainingQuestionaire().getInterest();
        if(!Interest.equalsIgnoreCase("")){
        trainingInterestCombo.setEnabled(true);
        trainingInterestCombo.setSelectedItem(Interest );
        specificComboYes.setSelected(true);
        seekLabel.setEnabled(true);
        }
        else
        {
            specificComboYes.setSelected(false);
            
        }
         String duration =questionaire.getTrainingQuestionaire().getTrainingDuration().equalsIgnoreCase("None") ?"":questionaire.getTrainingQuestionaire().getTrainingDuration();
        trainingDurationCombo.setSelectedItem(duration);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton btnRequestJob;
    private javax.swing.JPanel criminalPanel;
    private javax.swing.ButtonGroup disabilityCombo;
    private javax.swing.JRadioButton disabilityNo;
    private javax.swing.JComboBox<String> disabilityType;
    private javax.swing.JRadioButton disabilityYes;
    private javax.swing.JLabel disableLabel;
    private javax.swing.JPanel educationPanel;
    private javax.swing.JRadioButton extendedRadioBtn;
    private javax.swing.JPanel familyBackPanel;
    private javax.swing.ButtonGroup familyCombo;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel jobPanel;
    private javax.swing.JLabel loggedinLabel5;
    private javax.swing.JRadioButton nuclearRadioBtn;
    private javax.swing.JLabel orgLbl5;
    private javax.swing.JRadioButton parentRadioBtn;
    private javax.swing.JRadioButton receivedTrainingNo;
    private javax.swing.JRadioButton receivedTrainingYes;
    private javax.swing.JLabel roleLbl5;
    private javax.swing.JLabel seekLabel;
    private javax.swing.JRadioButton siblingRadioBtn;
    private javax.swing.JLabel skillLabel;
    private javax.swing.ButtonGroup specificCombo;
    private javax.swing.JRadioButton specificComboNo;
    private javax.swing.JRadioButton specificComboYes;
    private javax.swing.ButtonGroup trainingCombo;
    private javax.swing.JComboBox<String> trainingDurationCombo;
    private javax.swing.JComboBox<String> trainingInterestCombo;
    private javax.swing.JComboBox<String> trainingType;
    // End of variables declaration//GEN-END:variables
}
